version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    ports:
      - 5432:5432

  back:
    build:
      context: back
      target: development
    volumes:
      - ./back:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - 3000:3000 # webserver
      - 3001:9229 # debug
    command: npm run start:debug
    depends_on:
      - postgres
    environment:
      PORT: 3000
      TYPEORM_LOGGING: "true"
      TYPEORM_URL: postgresql://user:password@postgres:5432/user
